language: node_js
node_js:
  - lts/*
cache: yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - "eslint $(git diff --name-only $TRAVIS_BRANCH
 | grep -E \"(.*)\\.(jsx|js)$\" | xargs)"
  - yarn test --coverage
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
