name: Cypress

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup
        run: yarn install && yarn add -W serve
      - uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: http://0.0.0.0:3000
        with:
          browser: chrome
          build: yarn run build
          start: yarn serve
          wait-on: http://0.0.0.0:3000
